# Generated by Django 3.0.4 on 2020-03-21 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtype', models.CharField(choices=[('FA', 'Свободный ответ'), ('OA', 'Один вариант ответа'), ('MA', 'Несколько вариантов ответа')], max_length=2)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/question_images', verbose_name='Картинка')),
                ('text', models.TextField(blank=True, verbose_name='Текст вопроса')),
                ('number', models.IntegerField(default=-1, editable=False, verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['test_instance', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(editable=False, max_length=150)),
            ],
            options={
                'verbose_name': 'Категория тестов',
                'verbose_name_plural': 'Категории тестов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TestInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=150, verbose_name='Тема')),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', related_query_name='test', to='tester.TestCategory')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'ordering': ['category', 'theme'],
            },
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Текст')),
                ('is_correct', models.BooleanField(verbose_name='Правильный')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', related_query_name='choice', to='tester.Question')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответа',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', related_query_name='choice', to='tester.TestInstance'),
        ),
    ]
