# Generated by Django 3.0.4 on 2020-03-22 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('FA', 'Свободный ответ'), ('OA', 'Один вариант ответа'), ('MA', 'Несколько вариантов ответа')], max_length=2, verbose_name='Тип вопроса'),
        ),
        migrations.AlterField(
            model_name='testcategory',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='testcategory',
            name='slug',
            field=models.SlugField(max_length=150, verbose_name='Имя в ссылке'),
        ),
        migrations.AlterField(
            model_name='testinstance',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', related_query_name='test', to='tester.TestCategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='testinstance',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
