# Generated by Django 3.0.4 on 2020-03-22 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0002_auto_20200322_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='qtype',
        ),
        migrations.AlterField(
            model_name='question',
            name='test_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', related_query_name='question', to='tester.TestInstance', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='questionchoice',
            name='text',
            field=models.CharField(max_length=120, verbose_name='Текст'),
        ),
    ]
