# Generated by Django 3.0.4 on 2020-03-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0003_auto_20200322_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='descriptions',
            field=models.CharField(blank=True, max_length=150, verbose_name='Описание'),
        ),
    ]
