# Generated by Django 3.0.4 on 2020-03-22 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0004_question_descriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='descriptions',
            new_name='description',
        ),
    ]
