# Generated by Django 3.0.4 on 2020-03-22 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0005_auto_20200322_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testinstance',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.RenameField(
            model_name='testinstance',
            old_name='theme',
            new_name='name',
        ),
    ]
